name: zItems
author: Maxlego08
contributors: [ Traqueur_ ]
main: fr.maxlego08.items.ItemsPlugin
website: https://groupez.dev
description: Custom items
version: 1.0.0
api-version: 1.21
softdepend:
  - WorldGuard
commands: